version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample_app4
    ports:
      - "5050:5050"
    networks:
      - jenkinsnet

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:5050
    entrypoint:
      [
        "npx",
        "cypress",
        "run",
        "--reporter",
        "mochawesome",
        "--reporter-options",
        "reportDir=mochawesome-report,overwrite=false,html=true,json=false",
      ]
    networks:
      - jenkinsnet

networks:
  jenkinsnet:
    driver: bridge